### ISSUE TITLE
Documentation for gRPC client

### ISSUE THREAD

**Issue by ssraj326** [loopbackio/loopback4-extension-grpc#42]
# Description/Steps to reproduce
Im trying to setup gRpc client using service-proxy. But I couldnt find much help. I use Loopback4 in our project.

this link is also not updated yet. 
https://loopback.io/doc/en/lb4/gRPC-connector.html

would be great if we have some documentation for the grpc connector.

**Comment by dhmlau** [comment]
Cross posting from the Slack message https://loopbackio.slack.com/archives/C01177XQN8N/p1626389199060600 from @marioestradarosa:

---
Hi all!, I have just published a grpc-client example application along with a tutorial in the README.md file. This can be moved into the loopback4 repos as an example as soon as we polish it, in the mean time, I published it here because someone was asking for examples of integrating protocol buffers along with gRPC and loopback4.
https://github.com/marioestradarosa/loopback-grpc-client-example

**Comment by dhmlau** [comment]
Closing as resolved.
